//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApliRestExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int CursoID { get; set; }
        public string Titulo { get; set; }
    }
}
